#spring:
#  datasource:
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/mychatgpt?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    druid:
#      username: root
#      password: 123456
#      url: jdbc:mysql://localhost:3306/bear?serverTimezone=Asia/Shanghai
#      initial-size: 10
#      max-active: 10
#      max-wait: 6000
#      validation-query: SELECT 1 FROM DUAL
#      min-idle: 5
#      test-while-idle: true


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bear?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,slf4j
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000



#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/mychatgpt?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      max-wait: 60000
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 1
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      filters: stat,wall,slf4j
#      stat-view-servlet:
#        enabled: true
#        url-pattern: /druid/*
#        login-username: admin  # 设置登录 Druid 监控页面的用户名
#        login-password: admin  # 设置登录 Druid 监控页面的密码
#      web-stat-filter:
#        enabled: true
#        url-pattern: /*
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

logging:
  level:
    com.alibaba.druid: DEBUG


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    return-instance-for-empty-row: true